name: Discord Bot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🧪 Echo Environment Variables
        env:
          DISCORD_TOKEN: ${{ secrets.GITHUB_TOKEN.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GITHUB_TOKEN.GUILD_ID }}
          PROMPT_CHANNEL_ID: ${{ secrets.GITHUB_TOKEN.PROMPT_CHANNEL_ID }}
          PORT: ${{ env.PORT }}
        run: echo "Hello $DISCORD_TOKEN . $PORT"

      - name: 🚀 Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.GITHUB_TOKEN.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GITHUB_TOKEN.GUILD_ID }}
          PROMPT_CHANNEL_ID: ${{ secrets.GITHUB_TOKEN.PROMPT_CHANNEL_ID }}
          PORT: ${{ env.PORT }}
        run: npm run start
