name: Discord Bot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      PROMPT_CHANNEL_ID: ${{ secrets.PROMPT_CHANNEL_ID }}
      PORT: 3000

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Confirm secrets passed
        run: |
          echo "DISCORD_TOKEN is set: ${DISCORD_TOKEN:0:5}..."  # partial reveal
          echo "PORT is: $PORT"

      - name: 🚀 Run the bot
        run: npm run start
